### ISSUE TITLE
multiple scopes on client.profile doesn't work

### ISSUE THREAD

**Issue by sitch** [bobbrez/linkedin2#5]
Multiple scopes on client.profile doesn't work

``` ruby
LinkedIn::Client.new(scope: ['r_basicprofile', 'r_network'])
```

Oauth generates %5%B for the '[]'.  Need to implement a method that joins the scope on '%20'

http://developer.linkedin.com/documents/authentication#granting

Also for rails 1.9.3 the current string.reduce in LinkedIn::Client.profile_fields is no bueno

**Comment by bobbrez** [comment]
Multiscope is working for me on a project that I'm using this in. I'll investigate to see what's going on and try to put out a change before tomorrow.

Whoops, I'm using 2.1.0. I'll setup travis to test for that as well. If you are interested, feel fee to put together a PR for anything here if you think that will be quicker.

**Comment by bobbrez** [comment]
Resolved with the changes from today.
